### ISSUE TITLE
Crash using Angular + NS 2.5

### ISSUE THREAD

**Issue by eduardoturconi** [NativeScript/android-snapshot#16]
Hello,

When installing nativescript-dev-android-snapshot and running `tns run android --release` my app crashes immediately. My package.json has:

"nativescript": {
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-advanced-webview": "^1.1.3",
    "nativescript-angular": "^1.4.0",
    "nativescript-dev-webpack": "^0.3.3",
    "nativescript-hook": "^0.2.1",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-pulltorefresh": "^1.1.10",
    "nativescript-snackbar": "^1.1.6",
    "nativescript-telerik-ui": "^1.6.0-2017.2.13.3",
    "nativescript-theme-core": "^0.2.1",
    "nativescript-toast": "^1.4.5",
    "nativescript-web-image-cache": "^2.1.1",
    "nativescript-youtubesdk": "0.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.2",
    "tns-core-modules": "^2.5.0",
    "zone.js": "^0.7.2"
  }

Would this be an issue with not compatible nativescript-angular and tns-core-modules versions?

**Comment by ivanbuhov** [comment]
@eduardoturconi Can you provide the build log and the log from logcat?

**Comment by triniwiz** [comment]
@eduardoturconi  i had a similar problem because of the web pack plugin so i did `TNS_ANDROID_SNAPSHOT=0 tns run android --release` the app worked up until i started using the radlistview then it crashed

**Comment by daveware-nv** [comment]
I'm also getting this problem, the logcat suggests the problem is with an import from nativescript-angular

> Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/

which was referring to a line like:

> import {NativeScriptFormsModule} from "nativescript-angular";

changing it (and all other lines like it) to:

> import {NativeScriptFormsModule} from "nativescript-angular/forms";

seems to fix the issue.

**Comment by dtopuzov** [comment]
Snapshot is not longer included in angular template, since currently it is not compatible with webpack and it looks webpack and AOT give better performance.

We are working local snapshots, which will enable both snapshot and webpack to be applied on the same project. 
Stay tuned!
