### ISSUE TITLE
Snapshot fails the build if there are unsatisfied peerDependencies

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/android-snapshot#19]
Steps to reproduce:
```
tns create NGApp --ng
export TNS_ANDROID_SNAPSHOT=1
tns build android --path NGApp -> everthing is fine
cd NGApp 
npm i codelyzer@1.0.0-beta.2 --save-dev
cd ..
tns build android --path NGApp -> fail
```

Log:
```
Project successfully prepared (android)
Executing after-prepare hook from /Users/nsbuilduser/workspace/nativescript-ui-release-sdkAngular-android/NGApp/hooks/after-prepare/nativescript-dev-android-snapshot.js
ENOENT: no such file or directory, open '/Users/nsbuilduser/workspace/nativescript-ui-release-sdkAngular-android/NGApp/node_modules/nativescript-angular-snapshot/platform
```

Actually the problem is caused because when we have unsatisfied peer dependency `npm ls --json <some-package>` return output that we do not expect.
See: https://github.com/NativeScript/android-snapshot/blob/master/plugin/hooks/common.js#L95

**Comment by vchimev** [comment]
@ivanbuhov,

In addition, it'd be great if the snapshot errors about the real problem (UNMET PEER DEPENDENCY) and not afterward. Just to have it in mind for the local snapshots.
