### ISSUE TITLE
After-prepare fails if no <app name>/app/package.json file available

### ISSUE THREAD

**Issue by vchimev** [NativeScript/android-snapshot#3]
After-prepare hook of _nativescript-dev-android-snapshot_ fails to execute if there is no `<app name>/app/package.json` file available.

Might be it is a good idea to add a simple _package.json_ file in such scenario?

```
Project successfully prepared
Executing after-prepare hook from /Users/vchimev/Work/master/appTest/hooks/after-prepare/nativescript-dev-android-snapshot.js
ENOENT: no such file or directory, open '/Users/vchimev/Work/master/appTest/platforms/android/src/main/assets/app/package.json'
```

**Comment by jasssonpet** [comment]
The `package.json` is not strictly required for the application. I'll change the plugin to create one, if it doesn't exist.
