### ISSUE TITLE
Error in hook

### ISSUE THREAD

**Issue by bufke** [NativeScript/android-snapshot#4]
I'm following the tutorial nativescript app and instructions [here](https://docs.nativescript.org/runtimes/android/advanced-topics/V8-heap-snapshots) but it fails on tns build android. Using node v6.3.1 on Fedora Linux. Can't quite figure out where the error even is since that file is just a require.

```
Executing after-prepare hook from /home/david/Projects/ns/sample-Groceries/hooks/after-prepare/nativescript-dev-android-snapshot.js
Unexpected token 
 in JSON at position 130
```

**Comment by bufke** [comment]
I updated to the latest git master and this error went away. Maybe do a release when you get a chance. Thanks. It did bring down my start time by about a full second. Hope it gets even better in the future!

**Comment by jasssonpet** [comment]
Hi @bufke,
Thanks for using the plugin, we have just published the latest changes in npm.
