### ISSUE TITLE
Automate v8 version update

### ISSUE THREAD

**Issue by blagoev** [NativeScript/android-snapshot#5]
Currently the version is hardcoded in common.js file. We need to be able to automate this as much as possible. The final goal is to be able to download on the developer machine the correct snapshot for the current project's runtime version. Most probably we need to have the v8 version available somewhere in the project template.

Here's an example how we can output the correct v8 version from a build script:

```
$ echo '#include <stdio.h>\n#include "v8-version.h"\nint main() { printf("%d.%d.%d\\n", V8_MAJOR_VERSION, V8_MINOR_VERSION, V8_BUILD_NUMBER); }' | clang -xc - && ./a.out
$ 5.2.361
```

**Comment by jasssonpet** [comment]
https://github.com/NativeScript/android-runtime/commit/41e1f979452cce4365d3bdc4577a120140532ebe
