### ISSUE TITLE
Required heap snapshot package is not installed. Installing "nativescript-angular-snapshot@1.1.1-4.7.80".

### ISSUE THREAD

**Issue by adisoftbn** [NativeScript/android-snapshot#6]
Hello,

I cannot use android snapshot with angular. it needs a component that cannot be installed.

I have android 2.1.1
Native script 2.3
Android platform 2.3

```
Required heap snapshot package is not installed. Installing "nativescript-angular-snapshot@1.1.1-4.7.80".
Could not find package "nativescript-angular-snapshot@1.1.1-4.7.80" in the registry.
You can install it manually or remove the "nativescript-dev-android-snapshot" plugin and continue building without heap snapshots.
```

Best regards

**Comment by jasssonpet** [comment]
Hello, we are going to upload the new packages for the 2.4 release which is coming soon and are going to watch more closely that official releases match with the snapshot ones. If you still want to try the snapshot feature now I suggest that you downgrade nativescript-angular to 1.0.1 by changing your `package.json` dependencies to the ones [here](https://github.com/NativeScript/template-hello-world-ng/blob/6e7ca0dfbd71ab2dadaf4cd674de11e544b0600d/package.json#L30-L46) and try running it again.

**Comment by jasssonpet** [comment]
The 2.4 release is out: https://www.nativescript.org/blog/nativescript-2.4-announcement

I am closing this issue for now, please upgrade to the latest bits and feel free to open a new one if you have any issues.
