### ISSUE TITLE
Nativescript 2.4, Angular 2, Sample-Groceries: snapshot not found

### ISSUE THREAD

**Issue by andy-tai** [NativeScript/android-snapshot#9]
Building the Sample Geoceries (angular-end branch) with NativeScript 2.4.0, the build process shows errors of snapshots not found, although the end app runs fine on Android, with start-up time with no speedup from what snapshot may provide.

Installing the snapshot plug in, following the instructions, and then  try to build the Sample Groceries app, the following errors are show in the build log:

$ tns run android
Executing before-prepare hook from /home/atai/native_script_work/sample-Groceries.git/hooks/before-prepare/nativescript-dev-android-snapshot.js
Required heap snapshot package is not installed. Installing "nativescript-angular-snapshot@latest-1.1.2-5.2.361".
Could not find package "nativescript-angular-snapshot@latest-1.1.2-5.2.361" in the registry.
Build will now continue without using heap snapshots ...

the build system is Fedora 24 x86-64

**Comment by jasssonpet** [comment]
Hey, @andy-tai,

Can you update the version of nativescript-angular in the `package.json` to 1.1.3 and try running it again?

Snapshots are provided for only the latest tns-core-modules/nativescript-angular-snapshot and tns-android combinations, e.g. `nativescript-angular@1.1.2` works with `tns-android@2.3` only and `nativescript-angular@1.1.3` works with `tns-android@2.4` only.

**Comment by andy-tai** [comment]
OK, thanks.  I will try that.  Hopefully this information can be put in README or on the public page.  Right now I cannot find this detail anywhere.

**Comment by andy-tai** [comment]
Thanks, it worked.  Is there a way to find out what particular combinations of package versions have the snapshots available (say by examining a web site or ftp site)?  That will help people to use the snapshot plugin correctly.

**Comment by jasssonpet** [comment]
You can view the published packages in npm:
```shell
npm view tns-core-modules-snapshot dist-tags
npm view nativescript-angular-snapshot dist-tags
```

And here is what these versions mean: https://github.com/NativeScript/android-snapshot/tree/master/plugin#usage
